### ISSUE TITLE
Missing SMTP host exception despite using SpecifiedPickupDirectory

### ISSUE THREAD

**Issue by JustinStolle** [smsohan/MvcMailer#31]
When using SpecifiedPickupDirectory as the deliveryMethod in Web.config for testing (rather than Network with a host value), an InvalidOperationException is thrown with the message "The SMTP host was not specified."

   at System.Net.Mail.SmtpClient.CheckHostAndPort()
   at System.Net.Mail.SmtpClient.get_ServicePoint()
   at System.Net.Mail.SmtpClient.Dispose(Boolean disposing)
   at System.Net.Mail.SmtpClient.Dispose()
   at Mvc.Mailer.SmtpClientWrapper.Send(MailMessage mailMessage)
   at Mvc.Mailer.MailMessageExtensions.Send(MailMessage message, ISmtpClient smtpClient)
   at MySite.Controllers.UsersController.ResetPassword(String userName)

**Comment by JustinStolle** [comment]
The message does get "sent" to the specified pickup directory even though this error is thrown, but I'd prefer not to have to catch an InvalidOperationException just to ignore it.

**Comment by JustinStolle** [comment]
The workaround to this bug (that is closed as fixed, see [this item](http://connect.microsoft.com/VisualStudio/feedback/details/539160/smtpclient-reports-invalidoperationexception-when-disposed-immediatelly-after-sending-mail-and-pickup-directory-is-used)) is to add `<network host="localhost" />` (using "localhost" or any other value) to Web.config, but I'm curious if you think adding any handling code to the overridden `Send` method in `SmtpClientWrapper` class would be advised.

```
<system.net>
  <mailSettings>
    <smtp from="notify@domain.com" deliveryMethod="SpecifiedPickupDirectory">
      <specifiedPickupDirectory pickupDirectoryLocation="C:\temp\EmailPickup\" />
      <network host="localhost" />
    </smtp>
  </mailSettings>
</system.net>
```
